### ISSUE TITLE
HGP shifter not working on arch linux or linux mint (but works on windows 10)

### ISSUE THREAD

**Issue by krikcet** [Lawstorant/boxflat#74]
Hello, I'm failry new to Linux. Only been at it for about 6 months. Started with Linux mint. Built a new pc, and I'm running linux mint, windows 10 pro, and arch linux. on three separate nvme's mind you. Basically my issue is similar to the one mentioned here. My shifter works fine on windows. And before I built the new pc, I had the shifter working with boxflat and had the pidff as well on linux mint on the old pc. So everything was fantastic. Fast forward to today, I can't seem to get it to pick up the shifter, everything else works on both linux mint, and arch. I just made sure everything was updated today driver wise using the moza pithouse software on windows. I made sure everything was calibrated. Came over to arch (which is going to be my main linux distro moving forward.) Got everthing else working, but the shifter still isn't registering on arch. I've made sure to update all my packages. And still no dice. I'm assuming I'm doing something wrong considering I got this working before. But I can't seem to figure it out. It's a moza r12 base, with the hgp shifter, handbrake, and a couple wheels, and everything works except the shifter. (btw everything is run through the back of the base - and i did find the person on here who had a similar issue, which you said had been fixed when you updated it to have more inputs - so I'm figuring that's not the case. It's probably something I'm doing incorrectly.) Even tried calibrating it through the boxflat software. I'm assuming I missed something, but I'm not super familiar with what it could be. And this time around its saying that it isn't even connected. When before it said it was connected, but still didn't work, (and i did try calibrating it on boxflat multiple times previous) And I also am having the same problem on linux mint, except that it was showing connected, but not working. I feel like an idiot, but I'd love some advice.

**Comment by schetinind** [comment]
Hi! Thanks for the boxflat! I can confirm that my moza r5 and moaza hgp shifter refuse to connect after upgrading to the latest firmware version. On windows, everything is ok. before updating the firmware, the shifter connected but lost the connection after some time. after updating the firmware, the connection does not occur (device disconnected)

**Comment by Lawstorant** [comment]
I'll have to take a look if Moza didn't change anything on the firmware side. R9 here and everything works without issues but I do have everything connected through USB.

**Comment by Lawstorant** [comment]
Yup. Doesn't work with the latest firmware. I will look into this further after work.

**Comment by schetinind** [comment]
>  I'll check if there's any new firmware, but I won't support beta. If there are any changes, I'll only update when they release them as "stable".

Yes, the base,  wheel and pedals (all moza) are working fine. There are only problems with the shifter.

**Comment by Lawstorant** [comment]
Will be available on flathub in few hours

**Comment by krikcet** [comment]
> Will be available on flathub in few hours

Well, I have updated to v1.28.5 and it is still not working for me. 

![Image](https://github.com/user-attachments/assets/443cff3a-d109-47af-92ec-84bf9acde4ec)

![Image](https://github.com/user-attachments/assets/2dc0c3a1-a147-463e-adfb-639494ce7a53)

**Comment by krikcet** [comment]
Well I have updated to 1.28.5 and It's still not working for me. 


![Image](https://github.com/user-attachments/assets/92577f81-c769-4ed2-baa0-422c9a7f36da)

![Image](https://github.com/user-attachments/assets/91e190c6-0389-482f-8390-d55da074bd80)

**Comment by schetinind** [comment]
Hi there. Inalled latest version 1.28.5 and in my case the shifter connects only if I connect it via usb. in the case when the base and shifter are connected without usb and using transit, it is displayed that the device is not connected

**Comment by krikcet** [comment]
> Could you show me the output of:
> 
> ```
> ls -lah /dev/ | grep ACM
> ```
> 
> and:
> 
> ```
> ls -lah /dev/serial/by-id/
> ```

As soon as I get out of work I can get those for you. Thank you for the quick reply.

**Comment by Lawstorant** [comment]
That might not be necessary, but I'll still confirm that they are properly there. I found the issue and have to now think how to solve it. I think I need to finally sit down and figure out how to actually ask devices for their names, firmware versions etc.

**Comment by Lawstorant** [comment]
Should be fixed with #77

**Comment by krikcet** [comment]
Alright. So in boxflat, it is now stating that it is not disconnected anymore. But it won't calibrate, and it still isn't working in ATS or a couple other games I have tried so far. I'm going to send the responses for the things you asked for previously to see if that tells you anything. 

ls -lah /dev/ | grep ACM
crw-rw-rw-+  1 root    uucp   166,     0 Apr  1 19:32 ttyACM0

and for the second one 

ls -lah /dev/serial/by-id/
total 0
drwxr-xr-x 2 root root 60 Apr  1 19:27 .
drwxr-xr-x 4 root root 80 Apr  1 19:27 ..
lrwxrwxrwx 1 root root 13 Apr  1 19:27 usb-Gudsen_MOZA_R12_Base_2C0054000351333033363636-if00 -> ../../ttyACM0

**Comment by Lawstorant** [comment]
I'm kind of out of ideas. I just tested this with my R9, HGP, SGP shifter and they all work. Calibration works as well.

**Comment by Lawstorant** [comment]
Are you sure You have `universal-pidff-dkms-git` installed? And `linux-headers`?

**Comment by Lawstorant** [comment]
Could you share a screenshot from here: https://hardwaretester.com/gamepad?

**Comment by krikcet** [comment]
alright, that might be my problem. I was just trying to get universal-pidff-dkms-git installed. It says i have errors where i dont have the linux headers. So maybe that's why that isn't working and you're saying that aslo may be the cause of boxflat not reading the shifter?

**Comment by krikcet** [comment]
![Image](https://github.com/user-attachments/assets/5da5c20f-2205-4b2c-911d-8029ba00e221)

**Comment by krikcet** [comment]
![Image](https://github.com/user-attachments/assets/4c6396c5-008b-4128-9d3b-169bb116cca0)

**Comment by krikcet** [comment]
so i ran the makepkg -si again so i could recheck that. and yeah it looks like im missing the kernel headers.

**Comment by krikcet** [comment]
![Image](https://github.com/user-attachments/assets/9a7ee550-2a0f-4033-9617-8e01225f502f)

![Image](https://github.com/user-attachments/assets/693e5ed5-25d3-4f09-a178-ad17b22d2f44)

![Image](https://github.com/user-attachments/assets/d521b041-97c8-4570-8d68-fa394ec321b1)

**Comment by krikcet** [comment]
so i believe i resolved the linux header problem, but i have all those warnings for missing firmware. and i have no force feedback in game, and still no shifter showing up. i did recalibrate in boxflat. with no results.

**Comment by krikcet** [comment]
Thank you again. I just recently started using yay. That's how I installed and manage boxflat. But there were differences between the universal-pidff & universal-pidff-dkms-git on the aur page vs github. I believe I tried yay and it installed but didn't work. Then I installed dkms additionally. It still didn't work. So I just got the git file and did it that way. Still learning. The biggest issue anytime you learn something new, is you don't know what you don't know. And unfortunately I don't come from a programming background. But as a car mechanic I have the drive to figure things out and solve problems lol. But thanks again for everything.
